# Generated by Django 4.2.3 on 2023-09-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="friend",
            constraint=models.UniqueConstraint(
                condition=models.Q(("requester__lt", models.F("requestee"))),
                fields=("requester", "requestee"),
                name="unique_user_combination",
            ),
        ),
        migrations.AddConstraint(
            model_name="friend",
            constraint=models.CheckConstraint(
                check=models.Q(("requester", models.F("requestee")), _negated=True),
                name="different_users",
            ),
        ),
    ]
