# Generated by Django 4.2.3 on 2023-09-11 15:07

from django.db import migrations, models
import django.db.models.functions.comparison


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_remove_friend_unique_user_combination_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="friend",
            name="unique_user_combination",
        ),
        migrations.AddConstraint(
            model_name="friend",
            constraint=models.UniqueConstraint(
                django.db.models.functions.comparison.Least("requester", "requestee"),
                django.db.models.functions.comparison.Greatest(
                    "requestee", "requester"
                ),
                name="unique_user_combination",
            ),
        ),
    ]
