# Generated by Django 4.2.3 on 2023-09-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0005_remove_friend_different_users_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friend",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "PENDING"), ("ACCEPTED", "ACCEPTED")],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
