# Generated by Django 4.2.3 on 2023-09-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0007_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="ntype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("REACTION", "REACTION"),
                    ("COMMENT", "COMMENT"),
                    ("REPLY", "REPLY"),
                ],
                max_length=100,
                null=True,
                verbose_name="Type",
            ),
        ),
    ]
