# Generated by Django 4.2.3 on 2023-10-01 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("feed", "0001_initial"),
        ("profiles", "0008_notification_ntype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="feed.comment",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="ntype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("REACTION", "REACTION"),
                    ("COMMENT", "COMMENT"),
                    ("REPLY", "REPLY"),
                    ("ADMIN", "ADMIN"),
                ],
                max_length=100,
                null=True,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="feed.post",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="reply",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="feed.reply",
            ),
        ),
    ]
