# Generated by Django 4.2.3 on 2023-10-03 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "profiles",
            "0009_alter_notification_comment_alter_notification_ntype_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="ntype",
            field=models.CharField(
                choices=[
                    ("REACTION", "REACTION"),
                    ("COMMENT", "COMMENT"),
                    ("REPLY", "REPLY"),
                    ("ADMIN", "ADMIN"),
                ],
                default="REACTION",
                max_length=100,
                verbose_name="Type",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notification",
            name="receivers",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
