# Generated by Django 4.2.3 on 2023-10-03 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0010_alter_notification_ntype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="read_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="notifications_read",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
