# Generated by Django 4.2.3 on 2023-10-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0014_remove_notification_selected_object_constraints_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notification",
            name="selected_object_constraints",
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("comment", None), ("post__isnull", False), ("reply", None)
                    ),
                    models.Q(
                        ("comment__isnull", False), ("post", None), ("reply", None)
                    ),
                    models.Q(
                        ("comment", None), ("post", None), ("reply__isnull", False)
                    ),
                    models.Q(
                        ("comment", None),
                        ("ntype", "ADMIN"),
                        ("post", None),
                        ("reply", None),
                    ),
                    _connector="OR",
                ),
                name="selected_object_constraints",
                violation_error_message="Cannot have cannot have post, comment, reply or any two of the three simultaneously. If the three are None, then it must be of type 'ADMIN'",
            ),
        ),
    ]
