# Generated by Django 4.2.3 on 2023-10-05 08:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0017_remove_notification_sender_text_type_constraints_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="receivers",
            field=models.ManyToManyField(
                related_name="notifications", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
