# Generated by Django 4.2.3 on 2023-10-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "profiles",
            "0019_alter_notification_comment_alter_notification_post_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="host",
            field=models.CharField(editable=False, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="secured",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
