# Generated by Django 4.2.3 on 2023-10-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0020_notification_host_notification_secured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="text",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
