# Generated by Django 4.2.3 on 2023-10-09 21:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0021_alter_notification_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="host",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="secured",
        ),
    ]
