# Generated by Django 4.2.3 on 2024-01-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="access",
            field=models.TextField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="refresh",
            field=models.TextField(editable=False, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name="Jwt",
        ),
    ]
