# Generated by Django 4.2.3 on 2023-08-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_bio_user_city_user_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dob",
            field=models.DateTimeField(null=True, verbose_name="Date of Birth"),
        ),
    ]
