# Generated by Django 4.2.3 on 2023-08-26 14:37

import apps.accounts.models
import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_user_dob"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=autoslug.fields.AutoSlugField(
                default="fire",
                editable=False,
                populate_from=apps.accounts.models.slugify_two_fields,
                unique=True,
                verbose_name="Username",
            ),
            preserve_default=False,
        ),
    ]
