# Generated by Django 4.2.3 on 2023-08-31 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
        ("accounts", "0008_alter_user_avatar_alter_user_bio_alter_user_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cities_light.region",
            ),
        ),
    ]
