# Generated by Django 4.2.3 on 2023-09-04 23:16

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_alter_user_dob_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                editable=False,
                populate_from=["first_name", "last_name"],
                verbose_name="Username",
            ),
        ),
    ]
