#!/bin/bash

set -o errexit

set -o pipefail

set -o nounset

postgres_ready() {
python << END
import sys
import psycopg
try:
    psycopg.connect("host=${POSTGRES_SERVER} port=${POSTGRES_PORT} dbname=${POSTGRES_DB} user=${POSTGRES_USER} password=${POSTGRES_PASSWORD}")
except Exception as e:
    print(e)
    sys.exit(-1)
sys.exit(0)
END
}

until postgres_ready; do
 >&2 echo "Waiting for PostgreSQL to become available....:-("
 sleep 1
done
>&2 echo "PostgreSQL is ready!!!!...:-)"

exec "$@"
