# Generated by Django 4.2.3 on 2023-09-11 13:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="SocialNet", max_length=300)),
                (
                    "email",
                    models.EmailField(
                        default="kayprogrammer1@gmail.com", max_length=254
                    ),
                ),
                ("phone", models.CharField(default="+2348133831036", max_length=300)),
                (
                    "address",
                    models.CharField(default="234, Lagos, Nigeria", max_length=300),
                ),
                (
                    "fb",
                    models.CharField(
                        default="https://facebook.com",
                        max_length=300,
                        verbose_name="Facebook",
                    ),
                ),
                (
                    "tw",
                    models.CharField(
                        default="https://twitter.com",
                        max_length=300,
                        verbose_name="Twitter",
                    ),
                ),
                (
                    "wh",
                    models.CharField(
                        default="https://wa.me/2348133831036",
                        max_length=300,
                        verbose_name="Whatsapp",
                    ),
                ),
                (
                    "ig",
                    models.CharField(
                        default="https://instagram.com",
                        max_length=300,
                        verbose_name="Instagram",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Site details",
            },
        ),
    ]
