# Generated by Django 4.2.3 on 2023-08-25 23:25

import apps.feed.models
import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feed", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False,
                populate_from=apps.feed.models.slugify_two_fields,
                unique=True,
                verbose_name="slug",
            ),
        ),
    ]
