# Generated by Django 4.2.3 on 2023-08-25 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
        ("feed", "0002_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.file",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="reactions",
            field=models.ManyToManyField(blank=True, null=True, to="feed.reaction"),
        ),
    ]
