# Generated by Django 4.2.3 on 2023-08-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feed", "0003_alter_post_image_alter_post_reactions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="reactions",
            field=models.ManyToManyField(blank=True, to="feed.reaction"),
        ),
        migrations.AlterField(
            model_name="post",
            name="reactions",
            field=models.ManyToManyField(blank=True, to="feed.reaction"),
        ),
        migrations.AlterField(
            model_name="reply",
            name="reactions",
            field=models.ManyToManyField(blank=True, to="feed.reaction"),
        ),
    ]
