# Generated by Django 4.2.3 on 2023-08-28 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("feed", "0005_alter_post_options_comment_slug_reply_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reaction",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="comment",
            name="reactions",
        ),
        migrations.RemoveField(
            model_name="post",
            name="reactions",
        ),
        migrations.RemoveField(
            model_name="reply",
            name="reactions",
        ),
        migrations.AddField(
            model_name="reaction",
            name="comment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reactions",
                to="feed.comment",
            ),
        ),
        migrations.AddField(
            model_name="reaction",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reactions",
                to="feed.post",
            ),
        ),
        migrations.AddField(
            model_name="reaction",
            name="reply",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reactions",
                to="feed.reply",
            ),
        ),
    ]
