# Generated by Django 4.2.3 on 2023-09-01 18:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feed", "0007_alter_reaction_comment_alter_reaction_post_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reply",
            options={"verbose_name_plural": "Replies"},
        ),
    ]
