# Generated by Django 4.2.3 on 2023-09-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="chat",
            name="dm_chat_constraints",
        ),
        migrations.AlterField(
            model_name="chat",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="chat",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("ctype", "DM"),
                    ("description", None),
                    ("image", None),
                    ("name", None),
                    _negated=True,
                ),
                name="dm_chat_constraints",
            ),
        ),
    ]
