# Generated by Django 4.2.3 on 2023-09-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_remove_chat_dm_chat_constraints_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="description",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
