# Generated by Django 4.2.3 on 2023-09-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_alter_chat_description"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="chat",
            name="dm_chat_constraints",
        ),
        migrations.AddConstraint(
            model_name="chat",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("ctype", "DM"), ("ctype", "GROUP"), _connector="OR"),
                    ("name", None),
                    ("description", None),
                    ("image", None),
                ),
                name="dm_chat_constraints",
            ),
        ),
    ]
