# Generated by Django 4.2.3 on 2023-09-14 20:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0010_remove_chat_dm_chat_constraints_remove_chat_users_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="user_ids",
        ),
        migrations.AddField(
            model_name="chat",
            name="users",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
