# Generated by Django 4.2.3 on 2023-09-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0012_message"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="chat",
            name="dm_chat_constraints",
        ),
        migrations.AddConstraint(
            model_name="chat",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("ctype", "DM"),
                        ("description", None),
                        ("image", None),
                        ("name", None),
                    ),
                    models.Q(("ctype", "GROUP"), ("name__isnull", False)),
                    _connector="OR",
                ),
                name="dm_chat_constraints",
                violation_error_message="Chat with type 'DM' must have 'name', 'image' and 'description' as None",
            ),
        ),
    ]
