# Generated by Django 4.2.3 on 2023-09-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0016_remove_chat_dm_chat_constraints_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="chat",
            name="group_chat_constraints",
        ),
        migrations.RemoveConstraint(
            model_name="chat",
            name="dm_chat_constraints",
        ),
        migrations.AddConstraint(
            model_name="chat",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("ctype", "DM"),
                        ("description", None),
                        ("image", None),
                        ("name", None),
                    ),
                    ("ctype", "GROUP"),
                    _connector="OR",
                ),
                name="dm_chat_constraints",
                violation_error_message="DMs cannot have name, image and description",
            ),
        ),
        migrations.AddConstraint(
            model_name="chat",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("ctype", "GROUP"), ("name__isnull", False)),
                    ("ctype", "DM"),
                    _connector="OR",
                ),
                name="group_chat_constraints",
                violation_error_message="Enter name for group chat",
            ),
        ),
    ]
