# Generated by Django 4.2.3 on 2023-09-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0018_alter_message_options_alter_message_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
